#!/bin/sh
set -eu

BASE_DOMAIN="${PUBLIC_BASE_DOMAIN:-cuffmap.fesselspiel.com}"
OUT="${CUFFMAP_SUBDOMAIN_NGINX_CONF:-/etc/nginx/conf.d/cuffmap-user-subdomains.conf}"
TMP="${OUT}.tmp"
STATE_DIR="${CUFFMAP_STATE_DIR:-/var/lib/cuffmap}"
STATE_FILE="${STATE_DIR}/subdomain-cert-state"
PROXY_TARGET="${CUFFMAP_PROXY_TARGET:-http://127.0.0.1:8098}"
WEBROOT="${LETSENCRYPT_WEBROOT:-/var/www/certbot}"

mkdir -p "$STATE_DIR"

{
  echo "# Generated by cuffmap-refresh-subdomain-nginx. Do not edit manually."
  for live_dir in /etc/letsencrypt/live/*."$BASE_DOMAIN"; do
    [ -d "$live_dir" ] || continue
    domain="$(basename "$live_dir")"
    [ "$domain" != "$BASE_DOMAIN" ] || continue
    sub="${domain%."$BASE_DOMAIN"}"
    case "$sub" in
      *.*|""|*[!a-z0-9-]*) continue ;;
    esac
    [ -f "$live_dir/fullchain.pem" ] || continue
    [ -f "$live_dir/privkey.pem" ] || continue
    cat <<BLOCK

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ${domain};

    ssl_certificate ${live_dir}/fullchain.pem;
    ssl_certificate_key ${live_dir}/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 50m;

    location ^~ /.well-known/acme-challenge/ {
        root ${WEBROOT};
        default_type text/plain;
        try_files \$uri =404;
    }

    location / {
        proxy_pass ${PROXY_TARGET};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 300;
        proxy_send_timeout 300;
    }
}
BLOCK
  done
} > "$TMP"

cert_state="$(find /etc/letsencrypt/live /etc/letsencrypt/archive -type f -name "*.pem" -exec stat -c "%n:%Y:%s" {} \; 2>/dev/null | sort | sha256sum | cut -d" " -f1)"
old_state=""
[ -f "$STATE_FILE" ] && old_state="$(cat "$STATE_FILE")"

changed=0
if [ ! -f "$OUT" ] || ! cmp -s "$TMP" "$OUT"; then
  mv "$TMP" "$OUT"
  changed=1
else
  rm -f "$TMP"
fi

if [ "$cert_state" != "$old_state" ]; then
  printf "%s" "$cert_state" > "$STATE_FILE"
  changed=1
fi

if [ "$changed" -eq 1 ]; then
  nginx -t
  systemctl reload nginx
fi
